seed: 0

# IV_NO_OBS_CONFOUNDING
# IV_WITH_OBS_CONFOUNDING
# PCL
inference_mode: IV_WITH_OBS_CONFOUNDING

task: demand_design

algo: ctrl

dataset:
  seed: 0
  train_size: 5000
  test_size: 2000
  batch_size: 256
  unlabeled_size: 0
  use_high_dim_obs: True
  use_high_dim_treatment: True

network:
  use_image_feature: True
  gamma: 0.8 #1

  phi_dims: [512, 256, 32] 
  mu_dims: [16, 4] 
  xi_dims: [512, 256, 32] 
  nu_dims: [16, 4] 
  
  num_iter: 250
  eval_freq: 50
  lr: 5.e-4
  prob_loss_weight: 0.1
  aux_loss_weight: 0.5

sgd:
  num_iter: 20 
  eval_freq: 1

  batch_size: 128
  eta: 0.01 #0.005 

  reg_weight: 
    lambda_v: .01 #.1
    lambda_w: .01 #.1

  
  