seed: 0

# IV_NO_OBS_CONFOUNDING
# IV_WITH_OBS_CONFOUNDING
# PCL
inference_mode: IV_NO_OBS_CONFOUNDING

task: dsprites

algo: ctrl

dataset:
  seed: 0
  train_size: 5000
  test_size: 2000
  batch_size: 256 
  unlabeled_size: 0
  use_high_dim_obs: False

network:
  use_image_feature: False
  gamma: 1

  phi_dims: [1024, 512, 128, 32] # x: 4096
  mu_dims: [256, 128, 128, 32] # z: 3
  xi_dims: [] # not used

  num_iter: 50 
  eval_freq: 1
  lr: 5.e-4 
  prob_loss_weight: 0.1

sgd:
  num_iter: 90 
  eval_freq: 1

  batch_size: 1024 
  eta: 0.005 

  reg_weight: 
    lambda_v: 0.01
    lambda_w: 0.01

  